name: Build

on:
  push:
    branches-ignore: [ main ]

jobs:
  build-api:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: 'Build'
      run: |
        echo "$PWD"
        ls -a
  